import 'package:flutter/material.dart';

List<String> regions = [
  "Andijon",
  "Buxoro",
  "Fargʻona",
  "Jizzax",
  "Xorazm",
  "Namangan",
  "Navoiy",
  "Qashqadaryo",
  "Qoraqalpogʻiston",
  "Samarqand",
  "Sirdaryo",
  "Surxandaryo",
  "Toshkent vil.",
  "Toshkent shah."
];
List<Map<String, dynamic>> cities = [
  {
    "Andijon": [
      "Andijon shah.",
      "Andijon tum.",
      "Kuyganyor",
      "Asaka",
      "Baliqchi",
      "Boʻz",
      "Buloqboshi",
      "Izboskan",
      "Jalaquduq",
      "Xoʻjaobod",
      "Qoʻrgʻontepa",
      "Marhamat",
      "Oltinkoʻl",
      "Paxtabod",
      "Shahrixon",
      "Ulugʻnor"
    ]
  },
  {
    "Buxoro": [
      "Buxoro shah.",
      "Buxoro tum.",
      "Kogon",
      "Olot",
      "Gʻijduvon",
      "Jondor",
      "Qorakoʻl",
      "Qorovulbozor",
      "Peshku",
      "Romitan",
      "Shofirkon",
      "Vobkent"
    ]
  },
  {
    "Fargʻona": [
      "Farg‘ona shah.",
      "Marg‘ilon",
      "Quvasoy",
      "Qo‘qon",
      "Beshariq",
      "Bog‘dod",
      "Buvayda",
      "Dang‘ara",
      "Yozyovon",
      "Quva",
      "Qo‘shtepa",
      "Oltiariq",
      "Rishton",
      "So‘x",
      "Toshloq",
      "O‘zbekiston",
      "Uchko‘prik",
      "Farg‘ona tum",
      "Furqat",
    ]
  },
  {
    "Jizzax": [
      "Arnasoy",
      "Baxmal",
      "Doʻstlik",
      "Forish",
      "Gʻallarol",
      "Sharof Rashidov",
      "Mirzachoʻl",
      "Paxtakor",
      "Yangiobod",
      "Zomin",
      "Zafarobod",
      "Zarbdor",
    ],
  },
  {
    "Xorazm": [
      "Urganch",
      "Xiva",
      "Bog‘ot",
      "Gurlan",
      "Urganch",
      "Xiva",
      "Xonqa",
      "Hazorasp",
      "Shovot",
      "Yangiariq",
      "Yangibozor",
      "Qo‘shko‘pir",
    ]
  },
  {
    "Namangan": [
      "Namangan shah.",
      "Kosonsoy",
      "Mingbuloq",
      "Namangan tum.",
      "Norin",
      "Pop",
      "To‘raqo‘rg‘on",
      "Uychi",
      "Uchqo‘rg‘on",
      "Chortoq",
      "Chust",
      "Yangiqo‘rg‘on",
    ]
  },
  {
    "Navoiy": [
      "Navoiy shah.",
      "Zarafshon",
      "Karmana",
      "Konimex",
      "Navbahor",
      "Nurota",
      "Tomdi",
      "Uchquduq",
      "Xatirchi",
      "Qiziltepa",
    ]
  },
  {
    "Qashqadaryo": [
      "Qarshi shah.",
      "Shahrisabz",
      "Dehqonobod",
      "Kasbi",
      "Kitob",
      "Koson",
      "Mirishkor",
      "Muborak",
      "Nishon",
      "Chiroqchi",
      "Shahrisabz",
      "Yakkabog‘",
      "Qamashi",
      "Qarshi tum.",
      "G‘uzor",
    ]
  },
  {
    "Qoraqalpogʻiston": [
      "Nukus",
      "Amudaryo",
      "Beruniy",
      "Kegeyli",
      "Qanliko‘l",
      "Qorao‘zak",
      "Qo‘ng‘irot",
      "Mo‘ynoq",
      "Nukus",
      "Taxiatosh",
      "Taxtako‘pir",
      "To‘rtko‘l",
      "Xo‘jayli",
      "Chimboy",
      "Sho‘manoy",
      "Ellikqal’a",
    ]
  },
  {
    "Samarqand": [
      "Samarqand shah.",
      "Kattaqo‘rg‘on",
      "Bulung‘ur",
      "Jomboy",
      "Ishtixon",
      "Kattaqo‘rg‘on",
      "Narpay",
      "Nurobod",
      "Oqdaryo",
      "Payariq",
      "Pastdarg‘om",
      "Paxtachi",
      "Samarqand tum.",
      "Toyloq",
      "Urgut",
      "Qo‘shrabot",
    ]
  },
  {
    "Sirdaryo": [
      "Guliston shah.",
      "Yangiyer",
      "Shirin",
      "Boyovut",
      "Guliston tum.",
      "Mirzaobod",
      "Oqoltin",
      "Sardoba",
      "Sayxunobod",
      "Sirdaryo",
      "Xovos",
    ],
  },
  {
    "Surxandaryo": [
      "Termiz",
      "Angor",
      "Boysun",
      "Denov",
      "Jarqo‘rg‘on",
      "Muzrobod",
      "Oltinsoy",
      "Sariosiyo",
      "Termiz",
      "Uzun",
      "Sherobod",
      "Sho‘rchi",
      "Qiziriq",
      "Qumqo‘rg‘on",
    ]
  },
  {
    "Toshkent vil.": [
      "Nurafshon",
      "Angren",
      "Bekobod",
      "Olmaliq",
      "Ohangaron",
      "Chirchiq",
      "Yangiyo‘l",
      "Bekobod",
      "Bo‘ka",
      "Bo‘stonliq",
      "Zangiota",
      "Qibray",
      "Quyichirchiq",
      "Oqqo‘rg‘on",
      "Ohangaron",
      "Parkent",
      "Piskent",
      "Toshkent",
      "O‘rtachirchiq",
      "Chinoz",
      "Yuqorichirchiq",
      "Yangiyo‘l",
    ]
  },
  {
    "Toshkent shah.": [
      "Bektemir tumani",
      "Mirzo Ulug‘bek tumani",
      "Mirobod tumani",
      "Olmazor tumani",
      "Sirg‘ali tumani",
      "Uchtepa tumani",
      "Chilonzor tumani",
      "Shayxontohur tumani",
      "Yunusobod tumani",
      "Yakkasaroy tumani",
      "Yashnobod tumani",
    ]
  },
];
